config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'
  devise_for :users
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index,:show, :edit, :update]




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  # validates :title, presence: true
  # validates :body, presence: true

  validates :title, presence: true
  validates :body, presence: true,length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :books, dependent: :destroy

         has_one_attached :profile_image

  validates :name, presence: true,length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, presence: false,length: { maximum: 50 }



def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/images2/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

before_action :authenticate_user!, except: [:top, :about]
before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @books = Book.all
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end


  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    # @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.all
  end

  def update
    @book = Book.find(params[:id])
    @books = Book.all

    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
    flash[:notice] = 'You have updated user successfully.'
    redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
<div class="row">

<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
   <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

<div class="form-group">
  <%= f.submit 'Update Book',class: "btn btn-sm btn-success" %>
</div>

  <%=link_to "Show",book_path(@book.id)%>
   |
  <%=link_to "Back",books_path%>

<% end %>

app/views/books/index.html.erb
<!--<h1>Books</h1>-->

<!--<%# if @book.errors.any? %>-->
<!--  <%#= @book.errors.count %>件のエラーが発生しました-->
<!--  <ul>-->
<!--    <%# @book.errors.full_messages.each do |message| %>-->
<!--      <li><%#= message %></li>-->
<!--    <%# end %>-->
<!--  </ul>-->
<!--<%# end %>-->

<!--<%# @books.each do |book| %>-->
<!--<p>投稿ユーザー画像：<%#= image_tag book.user.get_profile_image(100,100) %></p>-->
<!--  <p>Title</p>-->
<!--  <span><%#= book.title %></span>-->
<!--  <p>Opinion</p>-->
<!--  <span><%#= book.body %></span>-->

<!--  <td><%#=link_to "Show",book_path(book.id)%></td>-->
<!--  <td><%#=link_to "Edit",edit_user_path(book.id)%></td>-->
<!--  <td><%#=link_to "Destroy",book_path(book.id), method: :delete, "data-confirm" => "Are you sure？"%></td>-->

<!--<%# end %>-->
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= flash[:notice] %>
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>


<div class='col-md-8 offset-md-1'>
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
        <%= link_to user_path(@user.id) do %>
        <%= image_tag @book.user.get_profile_image(80,80) %>
        <br><%= @user.name %>
        <% end %>
        </td>
        <td>
        <%= link_to @book.title,book_path(@book.id) %>
        </td>
        <td>
        <%= @book.body %>
        </td>
        <% if @book.user == current_user %>
        <td>
        <%=link_to "Edit",edit_book_path(@book.id), class: "btn btn-sm btn-success"%>
        </td>
        <td>
        <%=link_to "Destroy",book_path(@book.id),method: :delete, "data-confirm"=>"本当に消しますか？",  class: "btn btn-sm btn-danger"%>
        </td>
       <% end %>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div><td>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
     <h1 class="px-3 mx-auto">Welcome to  <i class="fas fa-book"></i> <strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

<footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<%= flash[:notice] %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i> <strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i> <strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in"  %>
        </div>
        <div class="row">
          <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-sm btn-block  sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>


  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html><head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
           <% if user_signed_in? %>

           <li class="nav-item">
            <%= link_to user_path(current_user), class:'nav-link text-light' do %>
            <i class="fas fa-home"></i> Home
            <% end %>
            <li>
            <%= link_to users_path, class:"nav-link text-light" do %>
            <i class="fas fa-users"></i> Users
            <% end %>
            </li>
            <li>
            <%= link_to books_path, class:"nav-link text-light" do %>
            <i class="fas fa-book-open"></i> Books
            <% end %>
            </li>
            <li>
            <%= link_to destroy_user_session_path, method: :delete, class:"nav-link text-light" do %>
            <i class="fas fa-sign-out-alt"></i> Log out
            <% end %>
            </li>
          </li>
           <% else %>

           <li class="nav-item">
            <%= link_to root_path, class:'nav-link text-light' do %>
            <i class="fas fa-home"></i> Home
            <% end %>
           </li>
           <li>
            <%= link_to about_path, class:"nav-link text-light" do %>
            <i class="fas fa-link"></i> About
             <% end %>
           </li>
           <li>
            <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
            <i class="fas fa-user-plus"></i> Sign up
            <% end %>
           </li>
           <li>
            <%= link_to user_session_path, class:"nav-link text-light" do %>
            <i class="fas fa-sign-in-alt"></i> Log in
            <% end %>
           </li>
           <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>


      <!--<li>-->
      <%#= link_to '投稿フォーム', new_book_path %>
      <!--</li>-->
      <!--<li>-->
      <%#= link_to 'マイページ', user_path(current_user.id) %>
      <!--</li>-->
      <!--<li>-->
        <%#= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <!--</li>-->

      <!--<li>-->
        <%#= link_to "新規登録", new_user_registration_path %>
      <!--</li>-->
      <!--<li>-->
        <%#= link_to "ログイン", new_user_session_path %>
      <!--</li>-->


   <%= yield %>
  </body>
</html>

app/views/users/_info.html.erb
<table class='table'>
  <!--<tr><%#= image_tag user.get_profile_image, size:'100x100' %></tr>-->
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this book from being saved:
  <ul>
   <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
   <% end %>
  </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <h2>User info</h2>
     <%= form_with model: @user do |f| %>

      <div class="form-group">
      <h4>Name</h4>
      <%= f.text_field :name, class: 'form-control book_title', autofocus: true, id:"inputName" %>
      </div>

      <div class="form-group">
      <h4>Image</h4>
      <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %>
      </div>

      <div class="form-group">
      <h4>Introduction</h4>

      <%= f.text_area :introduction, class: 'form-control book_body', autofocus: true, id:"inputBody" %>
      </div>
      <%= f.submit "Update User" %>
     <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>


  <div class='col-md-8 offset-md-1'>
  <h2>Users</h2>
  <table class="table">
   <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
   </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(80,80) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show",user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div>
  <%= image_tag @book.get_image %>
  <p>Title：<%= @book.shop_name %></p>
  <p>Opinion：<%= @book.caption %></p>
  <p>投稿ユーザー画像：<%= image_tag @book.user.get_profile_image(100,100) %></p>  <p>ユーザーネーム：<%= @book.user.name %></p>
  <p>投稿日時：<%= @book.created_at.strftime('%Y/%m/%d') %></p>
  <% if @book.user == current_user %>

  <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
    <%= link_to "削除", books_path(@book), method: :delete %>
  <% end %>
</div>